version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./Code/prometheus.yml:/etc/prometheus/Code/prometheus.yml
      - ./Cert/prometheus.crt:/etc/prometheus/prometheus.crt
      - ./Cert/prometheus.key:/etc/prometheus/prometheus.key
    ports:
      - "9090:9090"
    networks:
      - code_default

networks:
  code_default:
    driver: bridge
